sudo: require
services:
  - docker
script:
  - docker build . -t awnali/react-docker
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push awnali/react-docker
deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-131625054305"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_KEY"
  secret_access_key:
    secure: "$AWS_SECURE"
